CREATE TABLE `jnitboardmedia` (
  JNITMEDIA_ID NUMBER(10) NOT NULL,
  ORG_NM VARCHAR2(255) DEFAULT NULL,
  DST_NM VARCHAR2(255) DEFAULT NULL,
  SUCCESS_FLAG NUMBER(1) DEFAULT '0',
  CREATED datetime DEFAULT NULL,
  MODIFIED datetime DEFAULT NULL,
  ISDEL NUMBER(1) DEFAULT '0',
  PRIMARY KEY (`JNITMEDIA_ID`)
);